server:
  port: 8099
# 数据库相关的信息配置 TODO
spring:
    datasource:
      url: jdbc:postgresql://172.17.5.141:5432/gig_contract
      username: deliver_zhaopin
      password: deliver_zhaopin
      driver-class-name: com.mysql.jdbc.Driver