server:
  port: 8099
# 数据库相关的信息配置 TODO
spring:
    datasource:
      url: jdbc:postgresql://172.17.5.141:5432/gig_contract
      username: deliver_zhaopin
      password: deliver_zhaopin
      driver-class-name: org.postgresql.Driver
    redis:
      host: localhost
      port: 6379
#      cluster:
#        nodes:
#          - 172.17.90.50:6379
#          - 172.17.90.51:6379
#          - 172.17.90.52:6379
#        max-redirects: 1
#      lettuce:
#        pool:
#          max-wait: 1